version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Pub (Dart/Flutter)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Gradle (Android)
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
